chore(ut): BOOST_TEST -> BOOST_CHECK*s
reactivemarkets/toolbox-cpp pull request #214
Opened 2023-08-24 11:48 UTC by iakovs

2023-08-24 12:01 UTC, iakovs commented on .gitignore
> +.*.swp
Done.

2023-08-24 13:12 UTC, markaylett requested changes
Please do not format external contributions in "contrib" directory because this complicates future diffs/review when pulling latest changes from upstream.

2023-08-24 14:55 UTC, iakovs commented
> Please do not format external contributions in "contrib" directory because this complicates future diffs/review when pulling latest changes from upstream.

Sure thing. I didn't notice that. Then the first thing, I'll change the formatting script to exclude it

2023-08-24 16:18 UTC, iakovs commented
Done

> Please do not format external contributions in "contrib" directory because this complicates future diffs/review when pulling latest changes from upstream.

Done. And clang-format changed to exclude `/contrib/`

2023-08-25 06:42 UTC, markaylett approved these changes

2023-08-25 06:42 UTC, merged